apache/pulsar-client-reactive

- pulsar-client-reactive-adapter/src/intTest/java/org/apache/pulsar/reactive/client/adapter/ReactiveMessageConsumerE2ETest.java
- pulsar-client-reactive-adapter/src/intTest/java/org/apache/pulsar/reactive/client/adapter/ReactiveMessagePipelineE2ETest.java
- pulsar-client-reactive-adapter/src/intTest/java/org/apache/pulsar/reactive/client/adapter/ReactiveMessageReaderE2ETest.java
- pulsar-client-reactive-adapter/src/intTest/java/org/apache/pulsar/reactive/client/adapter/ReactiveMessageSenderE2ETest.java
- pulsar-client-reactive-adapter/src/main/java/org/apache/pulsar/reactive/client/internal/adapter/AdaptedReactiveMessageConsumer.java
- pulsar-client-reactive-adapter/src/main/java/org/apache/pulsar/reactive/client/internal/adapter/AdaptedReactiveMessageReader.java
- pulsar-client-reactive-adapter/src/main/java/org/apache/pulsar/reactive/client/internal/adapter/AdaptedReactiveMessageSender.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessageConsumer.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessageReader.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessageSender.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/internal/api/DefaultReactiveMessagePipeline.java
It's better to have unique names for methods which are operating on a single message or many messages.
These are different operations and have different semantics.
To be more consistent, a new naming convention of *One and *Many is introduced.
- The `readOne` and `consumeOne` methods should not be removed. They are different operations.
- These methods are needed for use cases where the application wants to read or consume exactly one or none messages
> Rename methods to use naming convention of [action]One and [action]Many

- README.adoc
The methods in README need to be renamed accordingly after #14
> Rename methods in README

- pulsar-client-reactive-adapter/src/main/java/org/apache/pulsar/reactive/client/internal/adapter/AdaptedReactiveMessageConsumer.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessageConsumer.java
It's easier to deal with the `Message` directly in the handler rather than a `Mono`
> Simplify consumeOne API

- README.adoc
- pulsar-client-reactive-adapter/src/intTest/java/org/apache/pulsar/reactive/client/adapter/ReactiveMessagePipelineE2ETest.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessageConsumer.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactivePulsarClient.java
So it's not needed to have access to an instance of `ReactivePulsarClient` to create a pipeline.
See https://github.com/spring-projects-experimental/spring-pulsar/pull/198#discussion_r1017238347
> Move ReactivePulsarClient::messagePipeline to ReactiveMessageConsumer

- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessageConsumerBuilder.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessageReaderBuilder.java
For consistency with `ReactiveMessageConsumerBuilder::topic` and `ConsumerBuilder::topics`
> Rename ReactiveMessageConsumerBuilder::topicNames to ReactiveMessageConsumerBuilder::topics

- pulsar-client-reactive-api/src/test/java/org/apache/pulsar/reactive/client/api/ReactiveMessagePipelineTest.java
Fixes #68
Fixes #70
- max.updateAndGet might get called multiple times when there are races
> Fix InflightCounter used in ReactiveMessagePipelineTest

- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/internal/api/InflightLimiter.java
- pulsar-client-reactive-api/src/test/java/org/apache/pulsar/reactive/client/api/ReactiveMessagePipelineTest.java
- pulsar-client-reactive-api/src/test/java/org/apache/pulsar/reactive/client/internal/api/InflightLimiterTest.java
- InflightLimiter has some bugs in max request calculation. The logic was hard to understand and this PR also simplifies the code.
- InflightLimiter's maybeTriggerNext unnecessarily scheduled tasks on every emitted entry. This has been optimized.
- Optimize maybeTriggerNext to schedule a job only when there's pendingSubscriptions and there's a need to request more elements.
- An additional optimization was added to maybeTriggerNext scheduling that there will only be one job triggered at a time when the condition is true.
- test that requests or subscriptions don't go over the maxInflight limit
- the reason why subscriptions should also be limited is that if there are non-lazy Mono's that already do work at subscription time, the maxInflight limit wouldn't be effective. This is the case …
> Fix bugs in InflightLimiter and add tests

- pulsar-client-reactive-adapter/src/intTest/java/org/apache/pulsar/reactive/client/adapter/ReactiveMessageSenderE2ETest.java
- pulsar-client-reactive-adapter/src/main/java/org/apache/pulsar/reactive/client/internal/adapter/AdaptedReactiveMessageSenderBuilder.java
> Require cache when maxInflight is set for ReactiveMessageSenderBuilder

- .github/workflows/ci.yml
- NOTICE
- build.gradle
- buildSrc/build.gradle
- checkstyle/checkstyle.xml
- gradle/libs.versions.toml
- idea/codeStyleConfig.xml
- pulsar-client-reactive-adapter/build.gradle
- pulsar-client-reactive-api/build.gradle
- pulsar-client-reactive-jackson/build.gradle
- pulsar-client-reactive-producer-cache-caffeine/build.gradle
- see https://lists.apache.org/thread/87of21sctklvhx8hvg67hs30od8n3n0d
- add missing license headers
- add NOTICE file
- configure RAT plugin to check license headers
- add Gradle task "sourceTar" that will create a .tar.gz package without the Gradle wrapper (similar solution is used in Apache Calcite, Gradle wrapper remains in the Git repository)
> Fix ASF release requirements

- .gitignore
- README.adoc
- gradle.properties
- update versions in README
- fix some code examples
- bump development version to 0.1.1-SNAPSHOT
- add `bin/` to .gitignore (IntelliJ uses bin directory if tests are run with IntelliJ instead of Gradle, that's sometimes useful)
> Post release 0.1.0 changes: update README, bump development version

- .github/workflows/ci.yml
- use https://github.com/gradle/gradle-build-action#why-use-the-gradle-build-action which contains a GitHub Actions caching solution for Gradle.
> Improve Gradle configuration in GitHub Actions

- README.adoc
- gradle.properties
- pulsar-client-reactive-adapter/build.gradle
- pulsar-client-reactive-adapter/src/intTest/java/org/apache/pulsar/reactive/client/adapter/ReactiveMessageSenderE2ETest.java
- pulsar-client-reactive-producer-cache-caffeine-shaded/build.gradle
- pulsar-client-reactive-producer-cache-caffeine-shaded/src/main/java/org/apache/pulsar/reactive/client/producercache/CaffeineShadedProducerCacheProvider.java
- pulsar-client-reactive-producer-cache-caffeine-shaded/src/main/java/org/apache/pulsar/reactive/client/producercache/CaffeineShadedProducerCacheProviderFactory.java
- pulsar-client-reactive-producer-cache-caffeine-shaded/src/main/resources/META-INF/services/org.apache.pulsar.reactive.client.adapter.ProducerCacheProviderFactory
- pulsar-client-reactive-producer-cache-caffeine-shaded/src/test/java/org/apache/pulsar/reactive/client/producercache/CaffeineShadedProducerCacheProviderTest.java
This proposal adds a producer cache provider module that uses a shaded version of Caffeine which gives users an option to not force Caffeine on the classpath.
The non-shaded version supports the richer CaffeineSpec API for `<init>` whereas the shaded version exposes a few simple properties. 
cc: @cbornet @lhotari
> Add shaded Caffeine producer cache provider

- gradle/libs.versions.toml
- pulsar-client-reactive-adapter/src/intTest/java/org/apache/pulsar/reactive/client/adapter/SingletonPulsarContainer.java
- Update version in toml
- Simplify the docker image name in int tests as Pulsar 3.0.0 docker images are multi-architectured (no need for special Mac M1/M2 treatment).
Fixes #126
cc: @lhotari @cbornet
> build: Upgrade Pulsar version to 3.0.1

- pulsar-client-reactive-producer-cache-caffeine-shaded/build.gradle
The previous relocation mistakenly was using the prefix of "org.springframework.pulsar.shade" when it should not be vendor specific and instead be "org.apache.pulsar.reactive.shade".
Fixes #127 
cc: @cbornet @lhotari
> Rename relocation prefix of Caffeine producer cache provider

- pulsar-client-reactive-adapter/src/main/java/org/apache/pulsar/reactive/client/internal/adapter/ProducerCacheKey.java
- pulsar-client-reactive-adapter/src/test/java/org/apache/pulsar/reactive/client/internal/adapter/ProducerCacheKeyTests.java
- pulsar-client-reactive-producer-cache-caffeine-shaded/src/test/java/org/apache/pulsar/reactive/client/producercache/CaffeineShadedProducerCacheProviderTest.java
- pulsar-client-reactive-producer-cache-caffeine/src/test/java/org/apache/pulsar/reactive/client/producercache/CaffeineProducerCacheProviderTest.java
The key used to cache producers includes the producer schema. 
This works well for primitive schema types and for complex schema types when the schema is the exact same instance. However, the schema contract does not enforce equals/hashCode. 
This results in cases where 2 producers using the same type of schema are not matching in the cache (eg. Schema.JSON(<some-class>)). 
This commit fixes this by using the schema hash for matching rather than the schema itself.
ℹ️ **NOTE** we ran into this issue in Spring for Apache Pulsar and solved it the same way in [this PR](https://github.com/spring-projects/spring-pulsar/pull/43#issuecomment-1198050217). As part of the code review [alpreu](https://github.com/alpreu) investigated if `SchemaHash` was safe to use (wrt to private/public API) and we …
> Fix producer cache key for JSON schema

- scripts/validate_staging_repo.sh
It's pretty clumbersome to validate releases by creating a new application each time. 
A script could help automate this process.
This script validates that the staging repo contains the expected artifacts by building a simple application with Gradle that uses the artifacts.
```
./validate_staging_repo.sh 0.5.1 https://repository.apache.org/content/repositories/orgapachepulsar-1257/
```
Requires `gradle` to be installed. Use `sdk install gradle` to install with sdkman
> Add script for validating staging repository by building a simple app with Gradle

- .github/workflows/ci.yml
- buildSrc/src/main/groovy/pulsar-client-reactive.library-conventions.gradle
- gradle/libs.versions.toml
This proposal updates to Java 17 for building but retains Java 8 as the language level via the `options.release` flag.
The second commit takes advantage of the first and updates the spring javaformat to `0.0.42` (which relies on Java 17 compilation).
> Updates to Java 17 for building

- gradle.properties
> [!IMPORTANT]
> This is dependent on #189 and #190 (must be merged after)
This will begin the release process for `v0.5.8` once merged
> [Release 0.5.8] Update version to 0.5.8

- README.adoc
- buildSrc/src/main/groovy/pulsar-client-reactive.publish-conventions.gradle
- pulsar-client-reactive-bom/build.gradle
- settings.gradle
This commit introduces a BOM module to make consumption of the library more robust by avoid library version mismatches.
Resolves #193
> Add pulsar-client-reactive-bom module

- gradle/libs.versions.toml
This commit updates Project Reactor and other dependencies to the latest patch versions as follows:
- reactor to `3.6.12`
- junit-jupiter to `5.11.3`
- mockito to `5.14.2`
- testcontainers to `1.20.3`
> Update Reactor and various other libs

- README.adoc
- gradle.properties
This performs the following post-release steps for release 0.5.10
- Update latest version in README.adoc to 0.5.10
- Update next snapshot version to 0.5.11-SNAPSHOT
> [Release 0.5.10] Post release steps

- gradle.properties
This updates the project version from 0.5.x to the next minor 0.6.x, specifically `0.6.0-SNAPSHOT`. 
The reasoning is the update from Pulsar 3.3.x to 4.0.x warrants at least a minor bump.
> Update project version to 0.6.x

- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessagePipelineBuilder.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/internal/api/DefaultReactiveMessagePipeline.java
- pulsar-client-reactive-api/src/test/java/org/apache/pulsar/reactive/client/api/ReactiveMessagePipelineTests.java
Fixes #210
There was a bug in negative acknowledgement handling when the message handler function throws an exception. 
An exception would cause the whole pipeline to be restarted, which is not intended. 
The problem was that the message handler function wasn't wrapped with `Mono.defer` which captures possible exceptions.
This PR adds a test case, javadoc and fixes the issue.
> Fix negative acknowledgement handling for ReactiveMessagePipeline when message handler throws an exception

- gradle/libs.versions.toml
- matches version used in io.spring.javaformat:spring-javaformat-checkstyle
> Upgrade checkstyle version to 9.3

- gradle/libs.versions.toml
- pulsar-client-reactive-adapter/build.gradle
- pulsar-client-reactive-adapter/src/intTest/java/org/apache/pulsar/reactive/client/adapter/ReactiveMessagePipelineE2ETests.java
- pulsar-client-reactive-adapter/src/intTest/java/org/apache/pulsar/reactive/client/adapter/SingletonPulsarContainer.java
- pulsar-client-reactive-adapter/src/main/java/org/apache/pulsar/reactive/client/internal/adapter/ReactiveConsumerAdapter.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessagePipeline.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/internal/api/DefaultReactiveMessagePipeline.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/internal/api/InternalConsumerListener.java
- pulsar-client-reactive-api/src/test/java/org/apache/pulsar/reactive/client/api/ReactiveMessagePipelineTests.java
Fixes #212
This adds `untilStarted` and `untilStopped` methods to `ReactiveMessagePipeline`.
`untilStarted` will get completed after calling `start` when the actual Pulsar consumer has been created. 
`untilStopped` will get completed after calling `stop` when the pipeline has been completely closed.
> Add untilStarted & untilStopped to ReactiveMessagePipeline

- pulsar-client-reactive-adapter/src/main/java/org/apache/pulsar/reactive/client/internal/adapter/AdaptedReactiveMessageConsumer.java
- pulsar-client-reactive-adapter/src/test/java/org/apache/pulsar/reactive/client/internal/adapter/AdaptedReactiveMessageConsumerTests.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ImmutableReactiveMessageConsumerSpec.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/MutableReactiveMessageConsumerSpec.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessageConsumerBuilder.java
- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ReactiveMessageConsumerSpec.java
- pulsar-client-reactive-api/src/test/java/org/apache/pulsar/reactive/client/api/ReactiveMessageConsumerBuilderTests.java
- pulsar-client-reactive-jackson/src/main/java/org/apache/pulsar/reactive/client/jackson/ImmutableReactiveMessageConsumerSpecMixin.java
- pulsar-client-reactive-jackson/src/main/java/org/apache/pulsar/reactive/client/jackson/PulsarReactiveClientModule.java
- pulsar-client-reactive-jackson/src/test/java/org/apache/pulsar/reactive/client/jackson/PulsarReactiveClientModuleTests.java
Since PR #213, setting a pulsar RedeliveryBackoff makes sense.
> Add redelivery backoff settings

- pulsar-client-reactive-api/src/main/java/org/apache/pulsar/reactive/client/api/ImmutableReactiveMessageConsumerSpec.java
This commit deprecates the current public constructor with all fields in favor of a package-protected variant. The constructor was initially added to support Jackson serde but it did not need to be public.
Resolves #221
> Deprecate public constructor in ImmutableReactiveMessageConsumerSpec
